### ISSUE TITLE
Error using holidays2json example

### ISSUE THREAD

**Issue by Laptopmini** [commenthol/date-holidays#101]
When attempting to create a custom build using the example
```
"scripts": {
  "build": "holidays2json --pick US,CA,MX --min"
},
```

I got the following
```
npm run build
Error: got #ifndef expected #elif, #else, #endif
    at Parser._isCmd (/Users/xxx/node_modules/prepin/lib/parser.js:55:13)
    at /Users/xxx/node_modules/prepin/lib/parser.js:43:17
    at Array.map (<anonymous>)
    at Parser.parse (/Users/xxx/node_modules/prepin/lib/parser.js:34:29)
    at /Users/xxx/node_modules/prepin/lib/index.js:20:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Using
```
$ npm -v
6.4.1
$ node -v
v8.12.0
```

Is it compatible with Node.js?

**Comment by Laptopmini** [comment]
The odd thing is that the countries available seem to change...

```
var Holidays = require('date-holidays');
    var hd = new Holidays();
    const countries = hd.getCountries();
    console.log(countries);
// { MX: 'México', US: 'United States of America' }
```

**Comment by commenthol** [comment]
Yes things are compatible with node. Problem is within the prepin package.

**Comment by commenthol** [comment]
prepin@1.0.3 released which fixes this issue.

**Comment by Laptopmini** [comment]
I would update the dependency rule as well:
`"prepin": "^1.0.3"`

**Comment by capatina** [comment]
This is still an issue. Same thing is happening:
![image](https://user-images.githubusercontent.com/13295539/115927009-c3d8be80-a451-11eb-9797-61bceb009c4c.png)
