### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by OliverHabersetzer** [commenthol/date-holidays#168]
I tried several configurations when trying to use typescript with this library:

**Initial setup**

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "lib": ["es2017", "esnext.asynciterable", "DOM"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noErrorTruncation": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "target": "es6"
  },
  "exclude": ["node_modules", "release"]
}
```

**My usage**

```typescript
import * as Holidays from 'date-holidays';
const holidays: Holidays = new Holidays();
// ...
const holiday = holidays.isHoliday(moment().toDate());
```

results in `node`, `ts-node` and `tsnd`:
```
(node:12220) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fn' of undefined
    at Holidays._dateByRule (C:\Users\WurstBroHD\Desktop\keenoras-den-bot\node_modules\date-holidays-parser\lib\Holidays.js:427:23)
    at Holidays.isHoliday (C:\Users\WurstBroHD\Desktop\keenoras-den-bot\node_modules\date-holidays-parser\lib\Holidays.js:288:31)
... (omitting my own files)
```

this is what I got after replacing the `import * as Holidays ...` with `import Holidays ...`:
```
 uncaughtException: date_holidays_1.default is not a constructor
TypeError: date_holidays_1.default is not a constructor
at Object.<anonymous> (C:\Users\WurstBroHD\Desktop\keenoras-den-bot\src\modules\Ranker.ts:14:28)
```
...with `Ranker.ts:14:28` being the line `const holidays: Holidays = new Holidays();`

Maybe this is related to #102 but they didn't give any useful info on the issue so I hope this helps!

If you don't know any fix to this, could you provide a known good `tsconfig.json`? Maybe my compiler settings are not the way you tested with TS.

**Comment by soullivaneuh** [comment]
Working for me with this implementation:

```typescript
// holidays.ts
import * as DateHolidays from 'date-holidays';

const holidays = new DateHolidays.default();

holidays.init('FR');

export default holidays;
```

**Comment by OliverHabersetzer** [comment]
Thanks, I'll try that one out. But it seems to be more of a workaround than a fix on the behalf of this library. 
In my opinion ts is very important to use - especially in bigger projects. 
Sometimes the types cause a bit of problems but in the end the compiler is able to keep you from making a lot of mistakes.

**Comment by OliverHabersetzer** [comment]
Nope, still the same error. it doesn't even recognize the `.default()` part. 
@soullivaneuh: could you provide more of your configuration / environment?

**Comment by jp928** [comment]
I have same error on 3.2.0

**Comment by kenmasumitsu** [comment]
When I set "esModuleInterop: true" in tsconfig.json, it worked.

tsconfig.json
```
{
  "compilerOptions": {
    ...
    "esModuleInterop": true,
  },
  ...
}
```

sample
```
import * as DateHolidays from 'date-holidays';
const x = new DateHolidays.default();
console.log(x);
```

**Comment by capc0** [comment]
im using 

```ts
import HolidayDefinition from 'date-holidays';

const germanCountryHolidays = new HolidayDefinition('de');
```

**Comment by zack-ccm** [comment]
I'm also seeing this issue with fresh create-react-app starting in version 3.

**Comment by tonganh** [comment]
> im using
> 
> ```ts
> import Holidays, * as HolidayDefinition from 'date-holidays';
> 
> const germanCountryHolidays = new (HolidayDefinition as any)('de') as Holidays;
> 
> console.log(germanCountryHolidays.getHolidays(2021))
> ```

This help me for that issue in Typescript.

**Comment by tiec7** [comment]
> Working for me with this implementation:
> 
> ```ts
> // holidays.ts
> import * as DateHolidays from 'date-holidays';
> 
> const holidays = new DateHolidays.default();
> 
> holidays.init('FR');
> 
> export default holidays;
> ```

I used this to make it work.

This issue is also open since more than a year, if you don't intend to fix it, would be nice at least to update documentation.

**Comment by mehrad-rafigh** [comment]
Following up on @winterec comment...I have to agree with him. Is there going to be a better Typescript support for this library?

**Comment by jukkaleh-atoz** [comment]
3.16.14 works fine with typescript 4.8.4

```
import Holidays from "date-holidays";
const hd = new Holidays("FI");
hd.setHoliday("04-30", {
  name: { en: "Labour Day's Eve", fi: "Vappuaatto" },
  type: "observance",
});
hd.setHoliday("easter -1", {
  name: { en: "Holy Saturday", fi: "Lankalauantai" },
  type: "observance",
});
hd.setHoliday("easter -3", {
  name: { en: "Maundy Thursday", fi: "Kiirastorstai" },
  type: "observance",
  });
const annualHolidays2023 = holidays.getHolidays(2023, "fi");
```

**Comment by mehrad-rafigh** [comment]
I stopped using this library, since my usecase was very small and I was able to use the Gauss Algorithm for detecting Easter Sunday. Everything else can be built on top of Easter Sunday.

**Comment by karlhorky** [comment]
Maybe related: the published types for `date-holidays@3.21.4` are apparently incorrect in a few different ways, as checked by Are The Types Wrong? by @andrewbranch:

(cc @commenthol)

[Are The Types Wrong?](https://arethetypeswrong.github.io/?p=date-holidays%403.21.4)

> 👺 [Masquerading as ESM](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md)
>
> Import resolved to an ESM type declaration file, but a CommonJS JavaScript file.
>
> ⚠️ [ESM (dynamic import only)](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSResolvesToESM.md)
>
> A require call resolved to an ESM JavaScript file, which is an error in Node and some bundlers. CommonJS consumers will need to use a dynamic import.
>
> 🐛 [Used fallback condition](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FallbackCondition.md)
>
> Import resolved to types through a conditional package.json export, but only after failing to resolve through an earlier condition. This behavior is a [TypeScript bug](https://github.com/microsoft/TypeScript/issues/50762). It may misrepresent the runtime behavior of this import and should not be relied upon.
>
> 💀 [Resolution failed](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/NoResolution.md)
>
> Import failed to resolve to type declarations or JavaScript files.
>
> ❌ [No types](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/UntypedResolution.md)
> 
> Import resolved to JavaScript files, but no type declarations were found.

![Screenshot 2023-08-27 at 16 25 29](https://github.com/commenthol/date-holidays/assets/1935696/937bca9d-8139-4b4e-999e-5bd924edd654)

**Comment by karlhorky** [comment]
Also some 2 errors and 2 warnings on `date-holidays@3.21.4 ` from [Publint](https://publint.dev/date-holidays@3.21.4):

> The types is not exported. Consider adding pkg.exports["."].import.types: "./types" to be compatible with TypeScript's "moduleResolution": "bundler" compiler option. ([More info](https://publint.dev/rules.html#types_not_exported))
>
> The types is not exported. Consider adding pkg.exports["."].require.types to be compatible with TypeScript's "moduleResolution": "bundler" compiler option. Note that you cannot use "./types" because it has a mismatching format. Instead, you can duplicate the file and use the .cts extension, e.g. pkg.exports["."].require.types: ".cts" ([More info](https://publint.dev/rules.html#types_not_exported))
>
> Should be the first in the object as required by TypeScript. ([More info](https://publint.dev/rules.html#exports_types_should_be_first))
>
> File does not exist ([More info](https://publint.dev/rules.html#file_does_not_exist))

![Screenshot 2023-08-27 at 16 26 07](https://github.com/commenthol/date-holidays/assets/1935696/8ecc4666-c2e3-48c4-bcc6-e9b8ef6f8a3a)

**Comment by johnnyPescarul** [comment]
Still having this same issue when running test on date-holidays version 3.23.8

**Comment by Tuai442** [comment]
I followed the recommendation provided by @kenmasumitsu, which resolved my initial issue. However, I encountered a new problem when using the getHolidays method.
> TypeError: Cannot read properties of undefined (reading 'apply')

````js
const hd = new Holidays();
hd.init('be', {
  languages: 'en',
});

const year = getYear(new Date());
const holidays = hd.getHolidays(year);
